name: CI workflow

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Unit tests
        run: npm test

      - name: Cypress E2E tests
        run: npm run test:e2e:ci

      - name: Upload cypress screenshots
        if: ${{failure()}}
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: ./cypress/screenshots

      - name: Upload cypress videos
        if: ${{failure()}}
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: ./cypress/videos    

  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
